FionaWhitfieldArt/Models/SearchViewModel.cs
using System.Collections.Generic;

namespace FionaWhitfieldArt.Models
{
    public class SearchViewModel
    {
        public string SearchTerm { get; set; }
        public string DocTypeAliases { get; set; }
        public string FieldPropertyAliases { get; set; }
        public int PageSize { get; set; }
        public int PagingGroupSize { get; set; }
        public string Category { get; set; }
        public List<SearchGroup> SearchGroups { get; set; }
        public SearchResultsModel SearchResults { get; set; }

    }
}

FionaWhitfieldArt/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using FionaWhitfieldArt.Models;
using Umbraco.Web;
using Umbraco.Core.Models;

namespace FionaWhitfieldArt.Controllers
{
    public class BlogController :SurfaceController
    {
        private string PartialViewPath(string name)
        {
            return "~/Views/Partials/Blog/" + name + ".cshtml";
        }

        public ActionResult RenderPostList(int numberOfItems)
        {
            IPublishedContent homePage = CurrentPage.AncestorOrSelf("home");
            List<BlogPreview> model = new List<BlogPreview>();
            IPublishedContent blogPage = homePage.Children.Where(x => x.DocumentTypeAlias == "blog").FirstOrDefault();

            foreach (IPublishedContent page in blogPage.Children.OrderByDescending( x => x.UpdateDate).Take(numberOfItems))
            {
                int imageId = page.GetPropertyValue<int>("articleImage");
                var mediaItem = Umbraco.Media(imageId);
                model.Add(new BlogPreview(page.Name, page.GetPropertyValue<string>("articleIntro"), mediaItem.Url, page.Url));
            }

            return PartialView(PartialViewPath("_PostList"), model);
        }

    }
}

FionaWhitfieldArt/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Umbraco.Web;
using Umbraco.Core.Models;
using Archetype.Models;
using FionaWhitfieldArt.Models;
using FionaWhitfieldArt.Library.Models;
using FionaWhitfieldArt.Library.Helpers;

namespace FionaWhitfieldArt.Controllers
{
    public class HomeController : SurfaceController
    {

        private string GetViewPath(string name)
        {
            return "~/Views/Partials/Home/" + name +".cshtml";
        }

        private const int MAXIMUN_TESTIMONIALS = 4;

        public ActionResult RenderFeatured()
        {
            HomeHelper homeHelper = new HomeHelper(CurrentPage, new UmbracoHelper(UmbracoContext.Current));
            List<FeaturedItem> model = homeHelper.GetFeaturedItemsModel();

            return PartialView(GetViewPath("_Featured"), model);
        }
  

        public ActionResult RenderBlog()
        {
            HomeHelper homeHelper = new HomeHelper(CurrentPage, new UmbracoHelper(UmbracoContext.Current));
            LatestBlogPosts model = homeHelper.GetLatestBlogPosts();
            return PartialView(GetViewPath("_Blog"), model);
        }

        

        public ActionResult RenderTestimonials()
        {
            IPublishedContent homePage = CurrentPage.AncestorOrSelf("home");

            string title = homePage.GetPropertyValue<string>("testimonialsTitle");
            string introduction = homePage.GetPropertyValue("testimonialsIntroduction").ToString();

            List<Testimonial> testimonialList = new List<Testimonial>();

            Testimonials model = new Testimonials(title, introduction, testimonialList);

            ArchetypeModel archetypeTestimonialList = homePage.GetPropertyValue<ArchetypeModel>("testimonialList");
            if (archetypeTestimonialList != null)
            {
                foreach (ArchetypeFieldsetModel testimonial in archetypeTestimonialList.Take(MAXIMUN_TESTIMONIALS))
                {
                    string name = testimonial.GetValue<string>("name");
                    string quote = testimonial.GetValue<string>("quote");
                    testimonialList.Add(new Testimonial(quote, name));

                }
            }
            return PartialView(GetViewPath("_Testimonials"), model);
        }


    }
}

FionaWhitfieldArt/Controllers/SearchController.cs
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using FionaWhitfieldArt.Models;
using Umbraco.Web;
using FionaWhitfieldArt.Helpers;
using System.Collections.Generic;

namespace FionaWhitfieldArt.Controllers
{
    public class SearchController : SurfaceController
    {
        #region Private Variables and Methods

        private SearchHelper _searchHelper { get { return new SearchHelper(new UmbracoHelper(UmbracoContext.Current)); } }

        private string PartialViewPath(string name)
        {
            return "~/Views/Partials/Search/" + name + ".cshtml";
        }

        private List<SearchGroup> GetSearchGroups(SearchViewModel model)
        {
            List<SearchGroup> searchGroups = null;
            if (!string.IsNullOrEmpty(model.FieldPropertyAliases))
            {
                searchGroups = new List<SearchGroup>();
                searchGroups.Add(new SearchGroup(model.FieldPropertyAliases.Split(','), new string[] { model.SearchTerm }));
            }
            if(!string.IsNullOrEmpty(model.Category))
            {
                if(searchGroups == null)
                {
                    searchGroups = new List<SearchGroup>();
                }
                searchGroups.Add(new SearchGroup(new string[] { "category" }, new string[] { model.Category }));
            }
            return searchGroups;
        }

        #endregion

        #region Controller Actions

        [HttpGet]
        public ActionResult RenderSearchForm(string query, string docTypeAliases, string fieldPropertyAliases, int pageSize, int pagingGroupSize)
        {
            SearchViewModel model = new SearchViewModel();
            if (!string.IsNullOrEmpty(query))
            {
                model.SearchTerm = query;
                model.DocTypeAliases = docTypeAliases;
                model.FieldPropertyAliases = fieldPropertyAliases;
                model.PageSize = pageSize;
                model.PagingGroupSize = pagingGroupSize;
                model.SearchGroups = GetSearchGroups(model);
                model.SearchResults = _searchHelper.GetSearchResults(model, Request.Form.AllKeys);
            }
            return PartialView(PartialViewPath("_SearchForm"), model);
        }

        [HttpPost]
        public ActionResult SubmitSearchForm(SearchViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(model.SearchTerm) || !string.IsNullOrEmpty(model.Category))
                {
                    model.SearchTerm = model.SearchTerm;
                    model.SearchGroups = GetSearchGroups(model);
                    model.SearchResults = _searchHelper.GetSearchResults(model, Request.Form.AllKeys);
                }
                return RenderSearchResults(model.SearchResults);
            }
            return null;
        }

        public ActionResult RenderSearchResults(SearchResultsModel model)
        {
            return PartialView(PartialViewPath("_SearchResults"), model);
        }

        #endregion

    }
}

FionaWhitfieldArt/Controllers/SiteLayoutController.cs
using FionaWhitfieldArt.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;
using Umbraco.Web;
using System.Runtime.Caching;

namespace FionaWhitfieldArt.Controllers
{
    public class SiteLayoutController : SurfaceController
    {

        private string PartialViewPath(string name)
        {
            return "~/Views/Partials/SiteLayout/" + name + ".cshtml";
        }
       
        public ActionResult RenderIntro()
        {
            return PartialView(PartialViewPath("_Intro"));
        }

        public ActionResult RenderTitleControls()
        {
            return PartialView(PartialViewPath("_TitleControls"));
        }

        public ActionResult RenderFooter()
        {
            return PartialView(PartialViewPath("_Footer"));
        }

        /// <summary>
        /// Renders the top navigation in the header partial
        /// </summary>
        /// <returns>Partial view with a model</returns>
        public ActionResult RenderHeader()
        {
            List<NavigationListItem> nav = GetObjectFromCache<List<NavigationListItem>>("mainNav", 5, GetNavigationModelFromDatabase);

            return PartialView(PartialViewPath("_Header"), nav);
        }


        /// <summary>
        /// Finds the home page and gets the navigation structure based on it and it's children
        /// </summary>
        /// <returns>A List of NavigationListItems, representing the structure of the site.</returns>
        private List<NavigationListItem> GetNavigationModelFromDatabase()
        {
            IPublishedContent homePage = CurrentPage.AncestorOrSelf("home");
            List<NavigationListItem> nav = new List<NavigationListItem>();
            nav.Add(new NavigationListItem(new NavigationLink(homePage.Url, homePage.Name)));
            nav.AddRange(GetChildNavigationList(homePage));
            return nav;
        }

        /// <summary>
        /// Loops through the child pages of a given page and their children to get the structure of the site.
        /// </summary>
        /// <param name="page">The parent page which you want the child structure for</param>
        /// <returns>A List of NavigationListItems, representing the structure of the pages below a page.</returns>
        private List<NavigationListItem> GetChildNavigationList(IPublishedContent page)
        {
            List<NavigationListItem> listItems = null;
            var childPages = page.Children.Where("Visible").Where(x => x.Level <= 2).Where(x => !x.HasValue("excludeFromTopNavigation") || (x.HasValue("excludeFromTopNavigation") && !x.GetPropertyValue<bool>("excludeFromTopNavigation")));
            if(childPages != null && childPages.Any() && childPages.Count() > 0)
            {
                listItems = new List<NavigationListItem>();
                foreach(var childPage in childPages)
                {
                    NavigationListItem listItem = new NavigationListItem(new NavigationLink(childPage.Url, childPage.Name));
                    listItem.Items = GetChildNavigationList(childPage);
                    listItems.Add(listItem);
                }
            }
            return listItems;
        }

        /// <summary>
        /// A generic function for getting and setting objects to the memory cache.
        /// </summary>
        /// <typeparam name="T">The type of the object to be returned.</typeparam>
        /// <param name="cacheItemName">The name to be used when storing this object in the cache.</param>
        /// <param name="cacheTimeInMinutes">How long to cache this object for.</param>
        /// <param name="objectSettingFunction">A parameterless function to call if the object isn't in the cache and you need to set it.</param>
        /// <returns>An object of the type you asked for</returns>
        private static T GetObjectFromCache<T>(string cacheItemName, int cacheTimeInMinutes, Func<T> objectSettingFunction)
        {
            ObjectCache cache = MemoryCache.Default;
            var cachedObject = (T)cache[cacheItemName];
            if (cachedObject == null)
            {
                CacheItemPolicy policy = new CacheItemPolicy();
                policy.AbsoluteExpiration = DateTimeOffset.Now.AddMinutes(cacheTimeInMinutes);
                cachedObject = objectSettingFunction();
                cache.Set(cacheItemName, cachedObject, policy);
            }
            return cachedObject;
        }

    }
}

FionaWhitfieldArt/Views/Blog.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@* the fun starts here *@

<div id="fh5co-blog-section">
    <div class="container">
        @{ Html.RenderAction("RenderTitleControls", "SiteLayout");}
        @{ Html.RenderAction("RenderPostList", "Blog", new { numberOfItems = 6 });}
    </div>
</div>

FionaWhitfieldArt/Views/BlogPost.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@* the fun starts here *@

<div id="fh5co-about-section">
    <div class="container about-inner">

        @{ Html.RenderAction("RenderTitleControls", "SiteLayout");}
        @CurrentPage.GetGridHtml("contentGrid", "bootstrap3")
        @*<blockquote>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
            </blockquote>*@


    </div>
</div>

FionaWhitfieldArt/Views/Contact.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@* the fun starts here *@

<div id="fh5co-contact-section">
		<div class="container">
			
            @{ Html.RenderAction("RenderTitleControls", "SiteLayout");}

			<div class="row">
				<div class="col-md-3">
					<h3>Contact Info.</h3>
					<ul class="contact-info">
						<li><i class="sl-icon-map"></i>198 West 21th Street, Suite 721 New York NY 10016</li>
						<li><i class="sl-icon-phone"></i>+ 1235 2355 98</li>
						<li><i class="sl-icon-envelope-open"></i><a href="#">info@yoursite.com</a></li>
						<li><i class="sl-icon-globe-alt"></i><a href="#">www.yoursite.com</a></li>
					</ul>
				</div>
				<div class="col-md-8 col-md-push-1 col-sm-12 col-sm-push-0 col-xs-12 col-xs-push-0">
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<input class="form-control" placeholder="Name" type="text">
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<input class="form-control" placeholder="Email" type="text">
							</div>
						</div>
						<div class="col-md-12">
							<div class="form-group">
								<textarea name="" class="form-control" id="" cols="30" rows="7" placeholder="Message"></textarea>
							</div>
						</div>
						<div class="col-md-12">
							<div class="form-group">
								<input value="Send Message" class="btn btn-primary" type="submit">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="map" data-animate-effect="fadeIn"></div>

@section ScriptsBottom
{
    <!-- Google Map -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCefOgb1ZWqYtj7raVSmN4PL2WkTrc-KyA&sensor=false"></script>
<script src="/scripts/google_map.js"></script>
}

FionaWhitfieldArt/Views/Content.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@* the fun starts here *@

<div id="fh5co-about-section">
    <div class="container about-inner">
        @{ Html.RenderAction("RenderTitleControls", "SiteLayout");}

        @CurrentPage.GetGridHtml("contentGrid", "bootstrap3")
        @*<blockquote>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
            </blockquote>*@


    </div>
	</div>

FionaWhitfieldArt/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}
@{Html.RenderAction("RenderIntro", "SiteLayout");}
@{Html.RenderAction("RenderFeatured", "Home");}
@{Html.RenderAction("RenderBlog", "Home");}
@{Html.RenderAction("RenderTestimonials", "Home");}

FionaWhitfieldArt/Views/Portfolio.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@* the fun starts here *@

<div id="fh5co-work-section">
		<div class="container">

			@{ Html.RenderAction("RenderTitleControls", "SiteLayout");}

			<div class="row">
				<div class="col-md-4 text-center">
					<div class="work-inner">
						<a href="#" class="work-grid" style="background-image: url(/images/image_1.jpg);">
						</a>
						<div class="desc">
							<h3><a href="#">Work with love</a></h3>
							<span>Web Design</span>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center">
					<div class="work-inner">
						<a href="#" class="work-grid" style="background-image: url(/images/image_2.jpg);">
						</a>
						<div class="desc">
							<h3><a href="#">Work with love</a></h3>
							<span>Web Design</span>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center">
					<div class="work-inner">
						<a href="#" class="work-grid" style="background-image: url(/images/image_3.jpg);">
						</a>
						<div class="desc">
							<h3><a href="#">Work with love</a></h3>
							<span>Web Design</span>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center">
					<div class="work-inner">
						<a href="#" class="work-grid" style="background-image: url(/images/image_4.jpg);">
						</a>
						<div class="desc">
							<h3><a href="#">Work with love</a></h3>
							<span>Web Design</span>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center">
					<div class="work-inner">
						<a href="#" class="work-grid" style="background-image: url(/images/image_5.jpg);">
						</a>
						<div class="desc">
							<h3><a href="#">Work with love</a></h3>
							<span>Web Design</span>
						</div>
					</div>
				</div>
				<div class="col-md-4 text-center">
					<div class="work-inner">
						<a href="#" class="work-grid" style="background-image: url(/images/image_6.jpg);">
						</a>
						<div class="desc">
							<h3><a href="#">Work with love</a></h3>
							<span>Web Design</span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

FionaWhitfieldArt/Views/Search.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}


@section Head
{
    <style>
        button.current { font-weight: 700; }
    </style>
}

    <section class="container">
        <div class="row">
            <div class="col-xs-12">
                @{ Html.RenderAction("RenderSearchForm", "Search", new { docTypeAliases = "blogPost,home", fieldPropertyAliases = "nodeName,metaName,metaKeyWords,metaDescription,contentGrid,intro", pageSize = 10, pagingGroupSize = 3 }); }
            </div>
        </div>
    </section>

@section ScriptsBottom{

    <!--You may not want to reference jQuery here if you already have it in your master template-->
    <script src="/scripts/jquery.validate.min.js"></script>
    <script src="/scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="/scripts/jquery.unobtrusive-ajax.js"></script>

    <script type="text/javascript">

        function debounce(func, wait, immediate) {
            var timeout;
            return function () {
                var context = this, args = arguments;
                var later = function () {
                    timeout = null;
                    if (!immediate) func.apply(context, args);
                };
                var callNow = immediate && !timeout;
                clearTimeout(timeout);
                timeout = setTimeout(later, wait);
                if (callNow) func.apply(context, args);
            };
        }

        $(document).on("click", "#submit-button", function (e) {
            e.preventDefault();
            var form = $(this).closest('form');
            $(form).submit();
        })

        $(document).on("keyup", "#SearchTerm", debounce(function (e) {
            e.preventDefault();
            var form = $(e.target).closest('form');
            $(form).submit();
        }, 300))

    </script>
}

FionaWhitfieldArt/Views/Services.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "WebBase.cshtml";
}

@* the fun starts here *@

<div id="fh5co-main-services-section">
		<div class="container">
			@{ Html.RenderAction("RenderTitleControls", "SiteLayout");}
			<div class="row">
				<div class="col-md-8">
					<div class="row">
						<div class="col-md-12 services-inner">
							<span><i class="sl-icon-graph"></i></span>
							<div class="desc">
								<h3>Finance Dashboard</h3>
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
							</div>
							</div>
						<div class="col-md-12 services-inner">
							<span><i class="sl-icon-heart"></i></span>
							<div class="desc">
								<h3>Made with Love</h3>
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
							</div>
						</div>
						<div class="col-md-12 services-inner">
							<span><i class="sl-icon-key"></i></span>
							<div class="desc">
								<h3>Help &amp; Support</h3>
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<aside class="sidebar">
						<div class="row">
							<div class="col-md-12 side">
								<h3>Categories</h3>
								<ul>
									<li><i class="icon-check"></i><a href="#">Web Design</a></li>
									<li><i class="icon-check"></i><a href="#">Branding &amp; Identity</a></li>
									<li><i class="icon-check"></i><a href="#">Free HTML5</a></li>
									<li><i class="icon-check"></i><a href="#">HandCrafted Templates</a></li>
									<li><i class="icon-check"></i><a href="#">Free Bootstrap Template</a></li>
									<li><i class="icon-check"></i><a href="#">Free HTML5 Template</a></li>
									<li><i class="icon-check"></i><a href="#">Free HTML5 &amp; CSS3 Template</a></li>
									<li><i class="icon-check"></i><a href="#">HandCrafted Templates</a></li>
								</ul>
							</div>
							<div class="col-md-12 side">
								<h3>Paragraph</h3>
								<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
							</div>
						</div>
					</aside>
				</div>
			</div>
		</div>
	</div>

FionaWhitfieldArt/Views/WebBase.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using System.Web.Optimization

@{
	Layout = null;
}


<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
 <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Lesser &mdash; Free HTML5 Bootstrap Website Template by FreeHTML5.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Website Template by FreeHTML5.co" />
    <meta name="keywords" content="free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="FreeHTML5.co" />
    <!--
      //////////////////////////////////////////////////////

      FREE HTML5 TEMPLATE
      DESIGNED & DEVELOPED by FreeHTML5.co

      Website: 		http://freehtml5.co/
      Email: 			info@freehtml5.co
      Twitter: 		http://twitter.com/fh5co
      Facebook: 		https://www.facebook.com/fh5co

      //////////////////////////////////////////////////////
       -->
    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content="" />
    <meta property="og:image" content="" />
    <meta property="og:url" content="" />
    <meta property="og:site_name" content="" />
    <meta property="og:description" content="" />
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="shortcut icon" href="favicon.ico">
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700,900' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700" rel="stylesheet">

    <!-- Animate.css -->
    <link rel="stylesheet" href="/css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="/css/icomoon.css">
    <!-- Simple Line Icons -->
    <link rel="stylesheet" href="/css/simple-line-icons.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <!-- Theme style  -->
    <link rel="stylesheet" href="/css/style.css">
    <!-- Modernizr JS -->
    <script src="/scripts/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="js/respond.min.js"></script>
    <![endif]-->

    @RenderSection("Head",false)
</head>
<body>
    @RenderSection("ScriptsTop", false)

    <div id="fh5co-page">

        @{Html.RenderAction("RenderHeader", "SiteLayout");}

        @RenderBody()
        
        @{Html.RenderAction("RenderFooter", "SiteLayout");}

    </div>


    <!-- jQuery -->
    <script src="/scripts/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="/scripts/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="/scripts/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="/scripts/jquery.waypoints.min.js"></script>
    
    @RenderSection("ScriptsBottom", false)

    <!-- MAIN JS -->
    <script src="/scripts/main.js"></script>

</body>
</html>